# Generated by Django 5.1.4 on 2025-01-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_remove_expense_created_by_expense_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('total_expense', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_costs', to='core.student')),
            ],
        ),
    ]
