# Generated by Django 5.1.4 on 2025-01-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('NB', 'Net Banking'), ('COD', 'Cash on Delivery'), ('MW', 'Mobile Wallet'), ('BT', 'Bank Transfer'), ('STR', 'Stripe'), ('PP', 'PayPal'), ('BTC', 'Bitcoin')], max_length=100),
        ),
    ]
